### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ALEGATOR1209** [ALEGATOR1209/BlutzBot#1]
- [ ] Solve phrases problems. Put it all into place they are called from or into single object with methods.
- [ ] Improve code readability. Remove repetitive code.
- [ ] Find free server and host bot there.
